image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 26.1.3-debian-12-r0
  pullPolicy: IfNotPresent

auth:
  adminUser: admin
  adminPassword: admin

postgresql:
  enabled: false  # Using external DB
externalDatabase:
  host: identitydb-postgresql
  user: keycloak
  password: keycloak
  database: keycloak

extraEnvVars:
  - name: KC_KEYSTORE_PASSWORD
    value: changeit
  - name: KC_HOSTNAME
    value: identity.virtual33.myguest.virtualbox.org
  - name: KC_HTTP_ENABLED
    value: "false"
  - name: KC_HTTPS_CLIENT_AUTH
    value: request
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: KC_PROXY
    value: "edge"

extraVolumes:
  - name: keycloak-certs
    secret:
      secretName: keycloak-certs

extraVolumeMounts:
  - name: keycloak-certs
    mountPath: /etc/x509/https
    readOnly: true

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 8443

ingress:
  enabled: true
  hostname: identity.virtual33.myguest.virtualbox.org
  ingressClassName: traefik
  tls: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  extraPaths: []
  pathType: ImplementationSpecific
  path: /

tls:
  enabled: true
  existingSecret: keycloak-certs
  keystoreFilename: keycloak.server.keystore.p12
  keystorePassword: changeit
  truststoreFilename: keycloak.client.truststore.p12
  truststorePassword: changeit
  keystoreAlias: keycloak
  usePem: false
  autoGenerated: false

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  size: 8Gi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false


