apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundle-server
  labels:
    app: bundle-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundle-server
  template:
    metadata:
      labels:
        app: bundle-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          volumeMounts:
            - name: bundle-volume
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: bundle-volume
          persistentVolumeClaim:
            claimName: bundle-pvc
      restartPolicy: Always

