apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundle-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundle-server
  template:
    metadata:
      labels:
        app: bundle-server
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared
              mountPath: /usr/share/nginx/html  # Directly set the mount path here
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: nfs-pvc  # Keep this as it is (refers to your PVC)

