apiVersion: v1
kind: PersistentVolume
metadata:
  name: bundle-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/bundles"  # Directory where bundle.tar.gz is stored

