apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bundle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bundle-pv  # Bind to the PV we created

