apiVersion: v1
kind: Service
metadata:
  name: opa-service
spec:
  selector:
    app: opa-kafka
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: ClusterIP  # Internal access only

