{{- range $name, $secret := .Values.keycloak.clientSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret-{{ $name | lower }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  client-secret: {{ $secret }}
---
{{- end }}

