apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: opa
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.1
          args:
            - "start"
            - "--https-key-store-file=/etc/x509/https/keycloak.server.keystore.p12"
            - "--https-key-store-password=$(KC_KEYSTORE_PASSWORD)"
            - "--https-key-store-type=PKCS12"
            - "--https-trust-store-file=/etc/x509/https/keycloak.client.truststore.p12"
            - "--https-trust-store-password=$(KC_KEYSTORE_PASSWORD)"
            - "--https-trust-store-type=PKCS12"
            - "--https-client-auth=request"
            - "--http-enabled=true"
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_KEYSTORE_PASSWORD
              value: "changeit"
            - name: KC_HOSTNAME
              value: "keycloak"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KEYCLOAK_DATABASE_HOST
              value: "identitydb-postgresql"
            - name: KEYCLOAK_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRESQL_DATABASE
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRESQL_USERNAME
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRESQL_PASSWORD
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
               secretKeyRef:
                 name: keycloak-db-secret
                 key: CONSOLE_SETUP_CLIENT_SECRET
            - name: KEYCLOAK_IMPORT
              value: "/opt/keycloak/data/import/realm-export.json"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: keycloak-certificates
              mountPath: /etc/x509/https
              readOnly: true
            - name: realm-export-volume
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: keycloak-certificates
          secret:
            secretName: keycloak-certificates
        - name: realm-export-volume
          configMap:
            name: realm-export-configmap

