apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: http
      name: http
    - port: 8443
      targetPort: https
      name: https
  selector:
    app: keycloak
  type: NodePort

