apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client-secret: {{ .Values.keycloak.clientSecrets.consoleSetup }}

