{{- if and .Values.keycloak.persistence .Values.keycloak.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  {{- range .Values.keycloak.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}
  storageClassName: {{ .Values.keycloak.persistence.storageClass }}
{{- end }}

