apiVersion: v1
kind: Secret
metadata:
  name: keycloak-certs
  namespace: keycloak
type: Opaque
data:
  keycloak.server.keystore.p12: |
    {{ YOUR_BASE64_ENCODED_KEYSTORE }}
  keycloak.client.truststore.p12: |
    {{ YOUR_BASE64_ENCODED_TRUSTSTORE }}
